# Generated by Django 4.1.2 on 2023-06-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0002_donationarea_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverypic', models.FileField(null=True, upload_to='')),
                ('crationdate', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationName', models.CharField(max_length=100, null=True)),
                ('donationpic', models.FileField(null=True, upload_to='')),
                ('colloctionloc', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=50)),
                ('donationdate', models.DateTimeField(auto_now_add=True)),
                ('adminRemarks', models.CharField(max_length=300, null=True)),
                ('volunteerRemarks', models.CharField(max_length=300, null=True)),
                ('updationDate', models.DateTimeField(null=True)),
                ('donationArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation.donationarea')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation.donor')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation.volunteer')),
            ],
        ),
    ]
