# Generated by Django 4.1.2 on 2023-06-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0003_gallery_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation.donation'),
        ),
    ]
