# Generated by Django 4.1.2 on 2023-06-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0004_alter_gallery_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Donation.donationarea'),
        ),
    ]
