# Generated by Django 4.1.2 on 2023-06-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0005_alter_donation_donationarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Donation.donationarea'),
        ),
    ]
